import "./globals.css";
import Sidebar from "@/Shared/page";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between items-center">

          <div className="w-[253px] h-[100vh]">
            <Sidebar />
          </div>

          <div className="children bg-[#191919] p-[50px]">
            {children}
          </div>

        </div>
      </body>
    </html>
  );
}
